!
frr version 10.5
frr defaults traditional
hostname R1
service integrated-vtysh-config
!
log syslog informational
!

interface lo
 ip address 101.0.0.254/32
 no shutdown
!

interface eth0
 ip address 101.0.0.9/30
 no shutdown
!

interface eth1
 ip address 101.0.0.1/30
 no shutdown
!

interface eth2
 ip address 101.0.0.5/30
 no shutdown
!

ip route 101.0.0.0/24 Null0
!

router bgp 64501
 bgp router-id 101.0.0.254

 network 101.0.0.0/24

 neighbor 101.0.0.2 remote-as 64500
 neighbor 101.0.0.6 remote-as 54502
 neighbor 101.0.0.10 remote-as 64503
!