!
frr version 10.5
frr defaults traditional
hostname cloud-r
service integrated-vtysh-config
!

interface lo
 ip address 103.0.0.1/32
 ip address 120.0.0.1/32
 no shutdown
!

interface eth1
 description bala-r
 ip address 101.0.0.10/30
 no shutdown
!

interface eth2
 description phcert-r
 ip address 102.0.0.10/30
 no shutdown
!

ip route 103.0.0.0/24 Null0
ip route 120.0.0.0/24 Null0
ip route 130.0.0.0/24 Null0

router bgp 64503
 no bgp ebgp-requires-policy

 network 103.0.0.0/24
 network 120.0.0.0/24

 neighbor 101.0.0.9 remote-as 64501
 neighbor 102.0.0.9 remote-as 54502
!