
ЗАДАНИЕ

Необходимо реализовать
    - R7 подключен к нашей AS 64500, при этом R7 имеет EBGP с нами используя приватный номер AS 64504
    - необходимо реализовать, чтобы при передаче в нашу AS 64500, в анонсах от R7 приватный номер AS 64504 затирался/менялся на наш 64500
 
Исходные данные
    - дана сеть из "Пошаговой настройки ibgp"


Решение (способ-1)
    - на стороне R7 к соседству c R4(64500) дописываем параметр local-as, который поменяет номер as в анонсе на 64500 
        router bgp 64504
        neighbor 100.0.0.5 local-as 64500


        
Третьим пунктом - проверка конфигурации
    - проверить что внутренняя AS-64500 выполняет транзит трафика провайдеров R5,R6,R7,R8
        - т.е. проверить  свяность R7----as64500-----(R5,R6,R8) и в обратную сторону


                        (64503)
                         --R8--
                --------|     |---------
                |                      |
            101.0.0.8/30            102.0.0.8/30    
                |                      |
         (64501)R5-----101.0.0.4/30----R6(64502)
                |                      |
            101.0.0.0/30           102.0.0.0/30
                |                      |
                |                      |
                |                      |
         (64500)R1-----10.0.12.0/24----R2(64500)  
                |                      |
            10.0.14.0/24           10.0.23.0/24
                |                      |
         (64500)R4-----10.0.34.0/24----R5(64500)
                |(.5)
                |
          100.0.0.4/30
                |   
                |(.6)
            R7(64504)
                



