
##указано только для R1
##для R2 настройка будет зеркальной, просто смотрим на эти настройки и схему и переносим все аналогично

###а ip sla тут не будет, так как это компромиссное решение
#.....
 
 
###выполняем настройку на базе local-pref
# через ISP 50... сети будут иметь local-pref 200
# через ISP 50... сети будут иметь local-pref 100

ip access-list standard CLIENT_FILIAL_1_NETS
 permit 50.1.1.0 0.0.0.255
ip access-list standard CLIENT_FILIAL_2_NETS
 permit 50.1.2.0 0.0.0.255э
ip access-list standard CLIENT_FILIAL_3_NETS
 permit 50.1.3.0 0.0.0.255
 
 
##to ISP-1
route-map INCOM-ANN-ISP-1 permit 10
  match ip address CLIENT_FILIAL_1_NETS
  match ip address CLIENT_FILIAL_2_NETS
  match ip address CLIENT_FILIAL_3_NETS
  set local-preference 200
route-map INCOM-ANN-ISP-1 permit 15

##to ISP-2
route-map INCOM-ANN-ISP-2 permit 10
  match ip address CLIENT_FILIAL_1_NETS
  match ip address CLIENT_FILIAL_2_NETS
  match ip address CLIENT_FILIAL_3_NETS
  set local-preference 100
route-map INCOM-ANN-ISP-2 permit 15


route-map INCOM-ANN-ISP-2 permit 40
  match ip address CLIENT_FILIAL_1_NETS
  set local-preference 200
route-map INCOM-ANN-ISP-2 permit 45

route-map INCOM-ANN-ISP-2 permit 50
  match ip address CLIENT_FILIAL_2_NETS
  set local-preference 200
route-map INCOM-ANN-ISP-2 permit 55

route-map INCOM-ANN-ISP-2 permit 60
  match ip address CLIENT_FILIAL_3_NETS
  set local-preference 200
route-map INCOM-ANN-ISP-2 permit 65


route-map INCOM-ANN-ISP-3 deny 10
 match ip address CLIENT_FILIAL_1_NETS
 match ip address CLIENT_FILIAL_2_NETS
 match ip address CLIENT_FILIAL_3_NETS
route-map INCOM-ANN-ISP-3 permit 20

route-map INCOM-ANN-IBGP permit 10
 match ip address CLIENT_FILIAL_1_NETS
 match ip address CLIENT_FILIAL_2_NETS
 match ip address CLIENT_FILIAL_3_NETS
 set local-preference 50
route-map INCOM-ANN-IBGP permit 20
