###Исходные основные настройки маршрутизации
    #На AS-100, AS-500, AS-1500, AS-1100, AS-1000
        #ebgp соседство между всеми указанными AS
    
    #На AS-500
        #не забыть что в ibgp соседство между всеми
        #не забыть что в ibgp нужно указывать neighbor x.x.x.x update-source

###Пошаговая настройка

    #(1) Согласно картинке 1-ым делаем передачу community запрещающее анонсировать
    #автономной системе AS-500 марршут дальше в другие AS
        #политика отправки community
        route-map ANN_POLICY permit 10
         match ip address prefix-list 10
         set community no-export
         route-map ANN_POLICY permit 20

        #применение политики route-map к  анонсам в сторону AS-500
            router bgp 100
            neighbor 10.0.240.254 remote-as 500
            neighbor 10.0.240.254 send-community
            neighbor 10.0.240.254 route-map ANN_POLICY out

        #результат - в AS-500 видим что эта сеть НЕ анонсируются другим EBGP
            show ip bgp 91.55.46.248
            BGP routing table entry for 91.55.46.248/30, version 19
            Paths: (1 available, best #1, table Default-IP-Routing-Table, not advertised to EBGP peer)
            Advertised to update-groups:
                    2
            100
                10.0.240.253 from 10.0.240.253 (91.55.46.253)
                Origin IGP, metric 0, localpref 100, valid, external, best
                Community: no-export
    #(2) Согласно картинке 2-ым запрещаем передачу подсети другим AS кроме 500-ой
    #все легко - делаем prefix-list + route-map

        #делаем route-map запрещающий анонс подсети
            ip prefix-list 20 seq 5 permit 91.55.46.248/30

            route-map ANN_DENY_2 deny 10
            match ip address prefix-list 20
            route-map ANN_DENY_2 permit 20

        #делаем пир-группу всех AS которые не AS-500, чтобы массово применить к ним route-map
            router bgp 100
            neighbor AS100 peer-group
            neighbor 10.0.10.10 peer-group AS100
            neighbor 10.0.20.2 peer-group AS100
            neighbor AS100 route-map ANN_DENY_2 out


    #(3) Дополнительный важный шаг - на ВСЕХ роутерах AS-500 
    #    включить передачу community, чтобы no-export для сети в анонсах сохранялись
        router bgp 500
        neighbor *.*.*.* send-community

    #Финальная проверка
        #На AS-500 
            #смотрим что 91.55.46.248/30 анонс лежит с строкой no-export
            show ip bgp 91.55.46.248
            
        #На всех остальных AS
            #смотрим что есть только анонс 91.55.46.252/30, а 91.55.46.248 отфильтрована
            show ip bgp 