!
frr version 10.5
frr defaults traditional
hostname link-r
service integrated-vtysh-config
!

interface lo
 ip address 100.0.0.254/32
 no shutdown
!

interface eth1
 description bala-r
 ip address 101.0.0.2/30
 no shutdown
!

interface eth2
 description phcert-r
 ip address 102.0.0.2/30
 no shutdown
!

ip route 100.0.0.0/24 Null0

#для подсети 0.0.0.0/0 все маски от 32 и ниже запрещены
#другими словами в этом префикс листекк запрещены все сети ipv4
ip prefix-list BALA-R-OUT seq 5 permit 100.0.0.0/24
ip prefix-list BALA-R-OUT seq 10 deny 0.0.0.0/0 ge 32


ip prefix-list PHCERT-R-OUT seq 5 permit 100.0.0.0/24
ip prefix-list PHCERT-R-OUT seq 10 deny 0.0.0.0/0 ge 32



router bgp 64500
 no bgp ebgp-requires-policy

 network 100.0.0.0/24

 neighbor 101.0.0.1 remote-as 64501
 neighbor 102.0.0.1 remote-as 54502
      
 #выставляем префикс листы ограничивающие анонсы
 #для более адвансед фич применяйте route-map и/или peer-group
 neighbor 101.0.0.1 prefix-list BALA-R-OUT out
 neighbor 102.0.0.1 prefix-list PHCERT-R-OUT out
!