

#balagan-router

hostname balagan-router

interface FastEthernet0/1
 description LinkMeUp_BGP
 ip address 101.0.0.1 255.255.255.252
 speed auto
 full-duplex

interface FastEthernet1/0
 description Philkin_Certificate_BGP
 ip address 101.0.0.5 255.255.255.252
 duplex auto
 speed auto

interface FastEthernet0/0
 description Cloud_BGP
 ip address 101.0.0.9 255.255.255.252
 speed 100
 full-duplex

router bgp 64501
 no synchronization
 bgp log-neighbor-changes
 network 101.0.0.0 mask 255.255.240.0
 neighbor 101.0.0.6 remote-as 64502
 neighbor 101.0.0.10 remote-as 64503
 no auto-summary

ip route 101.0.0.0 255.255.240.0 Null0

