#msk-arbat-gw1

hostname msk-arbat-gw1

interface Loopback1
ip address 10.0.1.1 255.255.255.0
ip nat inside

interface Loopback2
ip address 10.0.2.1 255.255.255.0
ip nat inside

interface FastEthernet0/1
 description Balagan_Telecom_Internet
 ip address 101.0.0.2 255.255.255.252
 ip nat outside
 duplex auto
 speed auto

interface FastEthernet0/0
 description Philkin_Certificate_Internet
 ip address 102.0.0.2 255.255.255.252
 ip nat outside
 speed 100
 full-duplex

exit

ip access-list extended LAN
permit ip 10.0.1.0 0.0.0.255 any
permit ip 10.0.2.0 0.0.0.255 any

route-map BALAGAN permit 10
 match ip address LAN
 match interface FastEthernet0/1

route-map PH_CERT permit 10
 match ip address LAN
 match interface FastEthernet0/0

ip nat inside source route-map BALAGAN interface Fa0/0 overload
ip nat inside source route-map PH_CERT interface Fa0/1 overload





###making policy routing via RouteMap+acl


#acl selector for policy routing
access-list 100 permit tcp 10.0.1.0 255.255.255.0 any eq 443
access-list 200 permit ip 10.0.2.0 255.255.255.0 any


route-map LAN_POLICY_1.0 permit 10
 match ip address 100
 set ip next-hop 101.0.0.1
route-amp LAN_POLICY_1.0 permit 20
 #cюда можно не ставить acl, будет применяться для остального трафика не попавшего под acl 100
 set interface Null0

route-map LAN_POLICY_2.0 permit 10
 match ip address 200
 set ip next-hop 102.0.0.2
route-map LAN_POLICY_2.0 permit 20
 #сюда можно не ставить acl, будет применяться для остального трафика не попавшего под acl 200
 set interface Null0

#не применяем policy-routing на loopback, а делаем специальную команду
#она отвечает за применение политик на трафик генерируемый самим маршрутизатором
ip local policy route-map LAN_POLICY_1.0
ip local policy route-map LAN_POLICY_2.0