
interface FastEthernet0/0
 description Link to R3
 ip address 192.168.3.4 255.255.255.0
 no shutdown
exit

interface FastEthernet0/1
 description Link to R2
 ip address 192.168.2.4 255.255.255.0
 no shutdown
exit

interface FastEthernet1/0
 description Link to R5
 ip address 192.168.100.4 255.255.255.0
 no shutdown
exit


conf t
ip route 0.0.0.0 0.0.0.0 192.168.2.2


###making policy routing via RouteMap+acl


#acl selector for policy routing
access-list 100 permit ip host 192.168.100.5 host 192.168.200.1

route-map BACK-to-200.1
match ip address 100 #policy selector - on acl 100
set ip next-hop 192.168.3.3 #policy action - setting next hop for selector

#policy can apply only on incoming traffic on int
#apply policy on int fa1/0 on r4
#...----r4(int fa1/0)(policy)<<---r5
int fa1/0
ip policy route-map BACK
