


            net 103.0.0.0/22
            net 120.0.0.0/24
              |
   |-------cloud-r--------|
   |                      |
bala-r               phcert-r   
   |                      |
   |------- link-r -------|
              |
            net 10.0.1.0/24
            net 10.0.2.0/24       
    
         



INFO:

on link-r
    - default gw is bala-r
    - nat traffic to providers
    - traffic comes as follows: link-r--phcert-r--cloud-r--intnets

on cloud-r
    - defult gw is bala-r
    - nat traffic to providers
    - traffic comes as follows: cloud-r--phcert-r--link-r--intnets

on bala-r and phcert-r 
    - routes to linked networks



TASK:
    (1)for link-r make pbr which make:
      - http traffic from 10.0.1.0/24 go to bala-r
      - ip traffic from 10.0.2.0/24 go to phcert-r
      - any other traffic must be dropped
    (2)additional exercise - pbr only woriking if:
      - both ISP (bala and phcert) are reacheable
      - otherwise device rib is used

ПОЯСНЕНИЯ:
    #route-map как PBR может быть только 1 на интерфейсе
    #поэтому делаем 1 PBR с списком 10,20,25,30
    #  10,20: сначала разрешающие правила для 10.х.х.х и правила их next-hop-а
    #  25:далее разрешающее правило для SLA трафика
    #  30:далее запрещаем все остальное для маршрутизации
     где 
      - 10-е правило pbr, это политики для 10.0.1.0
      - 20-е правило pbr, это политики для 10.0.2.0
      - 25-e правило pbr, это политики разрешающие SLA до провайдеров
      - 30-е правило pbr, политика route на Null всего остального трафика
    
    #исправить IP SLA 
      - указать для sla1 и sla2 source-interface
      -, чтобы проверки не уходили через другой интерфейс когда основной в down
    

КОНФИГ РЕШЕНИЯ:

#company-mamont(msk-router)


##

##SLA+track configs##
conf t

no ip sla 1
ip sla 1
icmp-echo 101.0.0.1 source-interface fa0/1
threshold 500
frequency 10
ip sla schedule 1 start-time now life forever

track 1 rtr 1
delay up 10 down 15

no ip sla 2
ip sla 2
icmp-echo 102.0.0.1 source-interface fa0/0
threshold 500
frequency 10
exit
ip sla schedule 2 start-time now life forever


track 2 rtr 2
delay up 10 down 15
exit


##acl selector for route-map PBR##

##selectors for routing localnets traffic
ip access-list extended PBR1.0
permit tcp 10.0.1.0 0.0.0.255 any eq www
exit

ip access-list extended PBR2.0
permit ip 10.0.2.0 0.0.0.255 any
exit

#selectors for SLA addresses
ip access-list extended SLA_Permissions_101
permit ip any host 101.0.0.1

ip access-list extended SLA_Permissions_102
permit ip any host 102.0.0.1


#deny - means not apply PBR for these
#permit - aply pbr rule for these
ip access-list extended DROP_Traffic_selector
deny ip 10.0.1.0 0.0.0.255 any
deny ip 10.0.2.0 0.0.0.255 any
permit ip any any 


##PBR##
route-map Net0.1-PBR permit 10
 match ip address PBR1.0
 set ip next-hop verify-availability 101.0.0.1 10 track 1

route-map Net0.1-PBR permit 20
 match ip address PBR2.0
 set ip next-hop verify-availability 102.0.0.1 10 track 2

route-map Net0.1-PBR permit 25
 match ip address SLA_Permissions_101
 set ip next-hop 101.0.0.1

route-map Net0.1-PBR permit 27
 match ip address SLA_Permissions_102
 set ip next-hop 102.0.0.1

route-map Net0.1-PBR permit 30
 match ip address DROP_Traffic_selector
 set interface Null0

