!
frr version 10.5
frr defaults traditional
hostname bala-r
service integrated-vtysh-config
!

interface lo
 ip address 101.0.0.254/32
 no shutdown
!

interface eth1
 description cloud-r
 ip address 101.0.0.9/30
 no shutdown
!

interface eth2
 description phcert-r
 ip address 101.0.0.5/30
 no shutdown
!

interface eth3
 description link-r
 ip address 101.0.0.1/30
 no shutdown
!

ip route 101.0.0.0/24 Null0

#prefix-list to filter everything except default gw route
ip prefix-list DEFAULT_ONLY seq 10 permit 0.0.0.0/0


router bgp 64501
 no bgp ebgp-requires-policy

 network 101.0.0.0/24

 #neigh to link-r with out announces with only 0.0.0.0
 neighbor 101.0.0.2 remote-as 64500
 neighbor 101.0.0.2 default-originate
 neighbor 101.0.0.2 prefix-list DEFAULT_ONLY out


 neighbor 101.0.0.2 remote-as 64500
 neighbor 101.0.0.6 remote-as 54502
 neighbor 101.0.0.10 remote-as 64503
!