###исходные данные
    #построенный ebgp с сосдеями as-64500
    #постороенная связность внутри AS-64500 на основе OSPF
    #построенный ibgp внутри AS 64500

###решение


    #делаем route-map и применяем к соседству с EBGP роутерами
    #в данном случае будет делать R1 более приоритеным для ibgp роутеров
    #поэтому ставим ему бОльший локал-преф

        #R1 бордер
            #конфигурация prefix-list который мэтчит 100.0.0.0/24 сеть
            #это сеть внутренней ibgp нам не нужно для нее ставить local-pref
            ip prefix-list 10 seq 5 permit 100.0.0.0/24

            #для всех сетей кроме 100.0.0.0/24 увеличиваем local-pref
            #для входящих анонсов от провайдера
            route-map EBGP_LOWER permit 10
              match ip address prefix-list 10
            route-map EBGP_LOWER permit 20
              set local-preference 200
            route-map EBGP_LOWER permit 30
              route-map EBGP_PREFERENCE permit 10
        
        #R2 бордер
            #применяем роут-мап для входяших анонсов провайдера
            router bgp 64500
              neighbor 102.0.0.1 route-map EBGP_LOWER in

            ip prefix-list 10 seq 5 permit 100.0.0.0/24
 
            route-map EBGP_LOWER permit 10
              match ip address prefix-list 10    
            route-map EBGP_LOWER permit 20
              set local-preference 150
            route-map EBGP_LOWER permit 30

    #проверяем конфигурацию
    

    #R1 bgp table
        #альтернативного маршрута через R2 нет, 
        #потому что 102 через этот роутер это лучший маршрут внутри IBGP
            show ip bgp
            Network          Next Hop            Metric LocPrf Weight Path
            *> 100.0.0.0/24     0.0.0.0                  0         32768 i
            * i                 100.0.0.2                0    100      0 i
            * i                 100.0.0.3                0    100      0 i
            *> 101.0.0.0/29     101.0.0.1                0    200      0 64501 i
            *> 102.0.0.0/30     101.0.0.1                     200      0 64501 64502 i

    #R2 bgp table
        #у R2 в свою очередь есть анонс и от EBGP и R1 
        #и на выбор у него два мршрута из которых он выибрает через R1 из-за local-pref
        show ip bgp
        Network          Next Hop            Metric LocPrf Weight Path
        * i100.0.0.0/24     100.0.0.1                0    100      0 i
        * i                 100.0.0.3                0    100      0 i
        *>                  0.0.0.0                  0         32768 i
        *>i101.0.0.0/29     100.0.0.1                0    200      0 64501 i
        *                   102.0.0.1                     150      0 64502 64501 i
        r>i102.0.0.0/30     100.0.0.1                0    200      0 64501 64502 i
        r                   102.0.0.1                0    150      0 64502 