!
frr version 10.5
frr defaults traditional
hostname link-r
service integrated-vtysh-config
!
log syslog informational
!
##basic controlplane config
interface eth1
 ip address 101.0.0.9/30
 no shutdown
!

interface eth2
 ip address 101.0.0.5/30
 no shutdown
!

interface eth3
 ip address 101.0.0.1/30
 no shutdown
!


##BGP
router bgp 64501
 bgp router-id 1.1.1.1
 bgp log-neighbor-changes

 network 101.0.0.0/20
 no bgp ebgp-requires-policy
 neighbor 101.0.0.6 remote-as 64502
 neighbor 101.0.0.6 description phcert-r

 neighbor 101.0.0.10 remote-as 64503
 neighbor 101.0.0.10 description cloud-r
!

ip route 101.0.0.0/20 Null0