hostname msk-arbat-gw1


interface Loopback1

ip address 10.0.1.1 255.255.255.0

ip nat inside

!

interface Loopback2

ip address 10.0.2.1 255.255.255.0

ip nat inside

!

interface FastEthernet0/0

description Balagan_Telecom_Internet

ip address 101.0.0.2 255.255.255.252

ip nat outside

duplex auto

speed auto

!

interface FastEthernet0/1

description Philkin_Certificate_Internet

ip address 102.0.0.2 255.255.255.252

ip nat outside

speed 100

full-duplex

!

!

ip access-list extended LAN

permit ip 10.0.1.0 0.0.0.255 any

permit ip 10.0.2.0 0.0.0.255 any

!

route-map BALAGAN permit 10

match ip address LAN

match interface FastEthernet0/0

route-map PH_CERT permit 10

match ip address LAN

match interface FastEthernet0/1

!

ip nat inside source route-map BALAGAN interface Fa0/0 overload

ip nat inside source route-map PH_CERT interface Fa0/1 overload


