hostname PhCert-router

!

interface FastEthernet0/0

 description Balagan_Telecom_BGP

 ip address 101.0.0.6 255.255.255.252

 duplex auto

 speed auto

!

interface FastEthernet0/1

 description LinkMeUp_BGP

 ip address 102.0.0.1 255.255.255.252

 speed 100

 full-duplex

!

interface FastEthernet1/0

 description Cloud_Internet

 ip address 102.0.0.9 255.255.255.252

 duplex auto

 speed auto

!

!

router bgp 64502

 no synchronization

 bgp log-neighbor-changes

 network 102.0.0.0 mask 255.255.248.0

 neighbor 101.0.0.5 remote-as 64501

 neighbor 102.0.0.10 remote-as 64503

 no auto-summary

!

ip route 102.0.0.0 255.255.248.0 Null0

