###show команды 
    #очистить информацию bgp без разрыва tcp сессии
    clear ip bgp * soft 
    #информация о полученных/отправленных в bgp table маршрутах
    show ip bgp neighbors 1.1.1.1 advertised-routes
    show ip bgp neighbors 1.1.1.1 received-routes