#Исходные настройки
    #доступность соседей BGP по линк сетям
    #настройка анонса по EBGP сетей указанных на рисунке


#(1)Удаление приватных as из as-path

###выполняем настройки на ISP маршрутизаторе
    #для соседа из анонсов которого хотим удалять номера приватных AS пишем
    neighbor 192.168.1.5 remove-private-as

    #проверяем отработку правил
    #третяя строчка AS 65000 удалена из as-path
    ISP> show ip bgp
    Network          Next Hop            Metric LocPrf Weight Path
    *> 10.1.1.0/24      0.0.0.0                  0         32768 i
    *> 10.2.2.0/24      192.168.1.6              0             0 300 i
    *> 10.3.3.0/24      192.168.1.6                            0 300 i


#(2)Фильтрация анонсов Company-1 другим AS

###выполняем настройки на ISP маршрутизаторе
    #фильтрация исходящих из Company-1(as-100) анонсов
    #именно сетей Company-1
    ip as-path access-list 100 permit .*100$

    #route-map с действием deny, который выполняет следующее
    # если внутри route-map COMP2-NO-ANOUNCE есть match
    # и если данный match с действием permit
    # , то не отрправляем этот анонс
    route-map COMP2-NO-ANOUNCE deny 10
    match as-path 100

    #применяем route-map COMP2-NO-ANOUNCE на интерфейсы откуда мы не хотим анонсить AS-100
    router bgp 300
    neighbor 172.24.1.18 route-map COMP2-NO-ANOUNCE out