
ЗАДАНИЕ

Необходимо реализовать
    - на маршрутизаторах соединяющихся по ebgp с внешними AS R1,R2,R4 реализовать фильтрацию получения маршрутов 
    - принимать анонс маршрута, только если в нем кол-во AS в AS-Path не превышает 10
    - принимать анонс маршрута, только если в нем маска не более /24

Исходные данные
    - дана сеть из "Пошаговой настройки ibgp"


Решение-1
    - на R1,R2,R4 включаем ограничение на кол-во AS в анонсах  
        - НЕДОСТАТОК - работает глобально для всех соседей
        #R1,R2,R4
        router bgp 64500
        bgp maxas-limit 10
        
Решение-2 
    - на R1,R2,R4 делаем
        - as-path acl на ограничение длины as-path 
        - применяем as-path на интерфейсы с входящим соседством ebgp

    - для 2-ого пункта делаем prefix-list с ограничением по маске сети 
        - смысл prefix-list таков 
        - первое правило запрещает информацию о маршрутах с маской 25 и больше 
        - второе правило, если первое пропустило, разрешает информацию о маршрутах с маской меньше 32,т.е от /0 до /32 
        #R1,R2,R4 
        ip prefix-list MASK deny 0.0.0.0/0 ge 25
        ip prefix-list MASK permit 0.0.0.0/0 le 32
        router bgp 64500
        neighbor <ebgp-neigh-address> remote-as 64504
        neighbor <ebgp-neigh-address> prefix-list MASK in


        
Третьим пунктом - проверка конфигурации
    - проверить что внутренняя AS-64500 выполняет транзит трафика провайдеров R5,R6,R7,R8
        - т.е. проверить  свяность R7----as64500-----(R5,R6,R8) и в обратную сторону


                        (64503)
                         --R8--
                --------|     |---------
                |                      |
            101.0.0.8/30            102.0.0.8/30    
                |                      |
         (64501)R5-----101.0.0.4/30----R6(64502)
                |                      |
            101.0.0.0/30           102.0.0.0/30
                |                      |
                |                      |
                |                      |
         (64500)R1-----10.0.12.0/24----R2(64500)  
                |                      |
            10.0.14.0/24           10.0.23.0/24
                |                      |
         (64500)R4-----10.0.34.0/24----R5(64500)
                |(.5)
                |
          100.0.0.4/30
                |   
                |(.6)
            R7(64504)
                



