hostname cloud-router

!

interface Loopback0

 ip address 103.0.0.1 255.255.255.255

!

interface Loopback1

 ip address 120.0.0.1 255.255.255.255

!

interface Loopback10

 ip address 103.0.0.10 255.255.255.255

!

interface Loopback20

 ip address 103.0.0.20 255.255.255.255

!

interface FastEthernet0/0

 description Balagan_Telecom_BGP

 ip address 101.0.0.10 255.255.255.252

 speed 100

 full-duplex

!

interface FastEthernet0/1

 description Philkin_Certificate_BGP

 ip address 102.0.0.10 255.255.255.252

 speed 100

 full-duplex

!

!

router bgp 64503

 no synchronization

 bgp log-neighbor-changes

 network 103.0.0.0 mask 255.255.252.0

 network 120.0.0.0 mask 255.255.255.0

 neighbor 101.0.0.9 remote-as 64501

 neighbor 102.0.0.9 remote-as 64502

 no auto-summary

!

ip route 103.0.0.0 255.255.252.0 Null0

ip route 120.0.0.0 255.255.255.0 Null0

!

ip http server