!
frr version 10.5
frr defaults traditional
hostname link-r
service integrated-vtysh-config
!
log syslog informational
!
##basic controlplane config
interface eth1
 ip address 102.0.0.9/30
 no shutdown
!

interface eth2
 ip address 101.0.0.6/30
 no shutdown
!

interface eth3
 ip address 102.0.0.1/30
 no shutdown
!

##BGP
router bgp 64502
 bgp router-id 3.3.3.3
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 network 102.0.0.0/21

 neighbor 101.0.0.5 remote-as 64501
 neighbor 101.0.0.5 description bala-r

 neighbor 102.0.0.10 remote-as 64503
 neighbor 102.0.0.10 description cloud-r
!

ip route 102.0.0.0/21 Null0