


            net 103.0.0.0/22
            net 120.0.0.0/24
              |
        |-------cloud-r--------|
        |                      |
        bala-r              phcert-r 
ann.net 101.0.0/20          ann.net 102.0.0/21
        |                      |
        |------- link-r -------|
                   |
               ann.net 100.0.0/23
      
    
         
INFO:
- default neighbor ebgp between 4 routers


TASK:
- сделай так чтобы link-r принимал только default-gw маршруты от phcert и bala-r
- для этого необходимо договориться с провайдерами чтобы они выполнили фильтрацию маршрутов в сторону link-r


КОНФИГ РЕШЕНИЯ:


### bala-r
#в frr конфиге bala-r добавляем 
#    - default-originate в сторону link-r
#    - и фильтрацию прочих маршрутов, чтобы даже если анонсы других проходили, то фильтровались

#prefix-list to filter everything except default gw route
ip prefix-list DEFAULT_ONLY seq 10 permit 0.0.0.0/0


###
router bgp 64501
 no bgp ebgp-requires-policy

 network 101.0.0.0/24

 #neigh to link-r with out announces with only 0.0.0.0
 neighbor 101.0.0.2 remote-as 64500
 neighbor 101.0.0.2 default-originate
 neighbor 101.0.0.2 prefix-list DEFAULT_ONLY out


###phcert-r

#тоже самое что и для bala-r
#    - default-originate в сторону link-r
#    - и фильтрацию прочих маршрутов, чтобы даже если анонсы других проходили, то фильтровались

#prefix-list to filter everything except default gw route
ip prefix-list DEFAULT_ONLY seq 10 permit 0.0.0.0/0



###
router bgp 54502
 no bgp ebgp-requires-policy

 network 102.0.0.0/24

 neighbor 101.0.0.5 remote-as 64501

 #neigh to link-r with out announces with only 0.0.0.0
 neighbor 102.0.0.2 remote-as 64500
 neighbor 102.0.0.2 default-originate
 neighbor 102.0.0.2 prefix-list DEFAULT_ONLY out