


            net 103.0.0.0/22
            net 120.0.0.0/24
              |
        |-------cloud-r--------|
        |                      |
        bala-r              phcert-r 
ann.net 101.0.0/20          ann.net 102.0.0/21
        |                      |
        |------- link-r -------|
                   |
               ann.net 100.0.0/23
      
    
         
INFO:
- default neighbor ebgp between 4 routers


TASK:
- link-r это по задумке тупиковая AS 
- сейчас она принимает анонсы от bala-r и phcert-r
- а далее отправляет полученные анонсы дальше 
- нам же нужно, чтобы link-r анонсировал только свою сеть 100.0.0.0/23
  транзитить трафик через себя AS link-r не должна

КОНФИГ РЕШЕНИЯ:

#добавляем prefix-list-ы, не будет заморачиваться тут с route-map или даже с peer-group
ip prefix-list BALA-R-OUT seq 5 permit 100.0.0.0/24
ip prefix-list BALA-R-OUT seq 10 deny 0.0.0.0/0 ge 32


ip prefix-list PHCERT-R-OUT seq 5 permit 100.0.0.0/24
ip prefix-list PHCERT-R-OUT seq 10 deny 0.0.0.0/0 ge 32

#добавляем peer-group на out анонсы к провайдерам phcert bala
 neighbor 101.0.0.1 prefix-list BALA-R-OUT out
 neighbor 102.0.0.1 prefix-list PHCERT-R-OUT out



##Подтверждаем конфигурацию тупиковой AS
#  


#На bala-r видим
# - от link-r 64500 анонсируется только 100.0.0.0/24 сеть
# видим что 100... пришла напрямую от link-r и от другого провайдера
# от 3-его провайдера тут анонса нет, так как 3-ий провайдер выбрал этот роутер как путь до 100...
bala-r# show ip bgp
Origin codes:  i - IGP, e - EGP, ? - incomplete
RPKI validation codes: V valid, I invalid, N Not found

     Network          Next Hop            Metric LocPrf Weight Path
 *>  100.0.0.0/24     101.0.0.2                0             0 64500 i
 *                    101.0.0.6                              0 54502 64500 i
 *>  101.0.0.0/24     0.0.0.0                  0         32768 i
 *>  102.0.0.0/24     101.0.0.6                0             0 54502 i
 *                    101.0.0.10                             0 64503 54502 i
 *>  103.0.0.0/24     101.0.0.10               0             0 64503 i
 *                    101.0.0.6                              0 54502 64503 i
 *>  120.0.0.0/24     101.0.0.10               0             0 64503 i
 *                    101.0.0.6                              0 54502 64503 i

#На phcert-r видим
# - от link-r 64500 анонсируется только 100.0.0.0/24 сеть
# видим что 100... пришла напрямую от link-r и от другого провайдера
# от 3-его провайдера тут уже видим анонс, это он анонсит маршрут до 100.. через bala-r

phcert-r# show ip bgp
Origin codes:  i - IGP, e - EGP, ? - incomplete
RPKI validation codes: V valid, I invalid, N Not found

     Network          Next Hop            Metric LocPrf Weight Path
 *>  100.0.0.0/24     102.0.0.2                0             0 64500 i
 *                    101.0.0.5                              0 64501 64500 i
 *                    102.0.0.10                             0 64503 64501 64500 i
 *>  101.0.0.0/24     101.0.0.5                0             0 64501 i
 *                    102.0.0.10                             0 64503 64501 i
 *>  102.0.0.0/24     0.0.0.0                  0         32768 i
 *>  103.0.0.0/24     102.0.0.10               0             0 64503 i
 *                    101.0.0.5                              0 64501 64503 i
 *>  120.0.0.0/24     102.0.0.10               0             0 64503 i
 *                    101.0.0.5                              0 64501 64503 i