#Исходные настройки
    #EBGP настроен между AS-1 и AS-2
    #AS-3 фактический нет и представлен в виде маршрутов на AS-2 маршрутизаторе
    #AS-3 также анонсятся от AS-2 к AS-1

#(AS-1)Анонсируем сети 10.1.1.1/30 и 10.2.2.2/24 как сеть класса А 10.0.0.0/8
    #В процессе bgp включаем auto-summary которое включает определение класса объявляемых сетей
    router bgp 1
    auto-summary
    #С включенным auto-summary bgp может определять класс сети указанной в network команде
    #Добавляем сеть 10.0.0.0, автоопределяется до сети /8
    router bgp 1
    network 10.0.0.0

#(AS-2)Анонсируем сети 172.16.[0-3].0/24 как сеть 172.16.0.0/23 суммирующая эти 4 сети

    #Создаем сеть 172.16.0.0/22 в rib чтобы оно могло попасть в bgp table
    ip route 172.16.0.0 255.255.252.0 Null0
    #Добавляем в процесс bgp маршрут до суммированной сети
    router bgp 2
    no synchronization
    bgp log-neighbor-changes
    network 172.16.0.0 mask 255.255.252.0

#(AS-2)Анонсируем сети 192.168.[24-27].0/24 как сеть 192.168.24.0/23 суммирующая эти 4 сети
    #Создаем сеть 192.168.24.0/22 в rib чтобы оно могло попасть в bgp table
    ip route 192.168.24.0 255.255.252.0 Null0
    #Добавляем в процесс bgp маршрут до суммированной сети
    router bgp 2
    no synchronization
    bgp log-neighbor-changes
    network 192.168.24.0 mask 255.255.252.0
