###атрибуты bgp анонсов 

    #у bgp есть куча возможных задаваемых атрибутов в анонсах
    #но as-path является обязательным распознаваемым атрибутом
        #является основным при выборе маршрута в rib из bgp table
        #на нем основан механизм предоствращение петель маршрутизации при передаче bgp маршрутов
    #поэтому на основе его обычно делаются манипуляции в route-map применяемых к соседям
        #как например в этой работе ухудшаем анонс от одного из соседей

### set параметр в route-map
    #с помощью set можно манипулировать не только as-path
    #но и другими атрибутами передаемых в анонсах bgp 
    #это нужно помнить и постепенно узнавать о бОльшем кол-ве атрибутов