#Исходные настройки
    #доступность соседей BGP по линк сетям
    #настройка анонса по EBGP сетей указанных на рисунке

#(1)Ухудшение приоритетности маршрута 192.168.13.0/24 на маршрутизаторе Company-1 через ISP-1

###выполняем настройки на Company маршрутизаторе
    #будем делать ухудшение анонса через ISP-1 через route-map

    #префикс-лист который будет определять для анонса какой сети будет применяться политика
    ip prefix-list LOW_PRIOR_NET seq 5 permit 192.168.13.0/24

    #делаем route-map,
    # для всех кто подошел (permit 10) по условиям match (LOW_PRIOR_NET)
    # выполняем добавление доп. номера as в as-path анонса
    route-map AS_PATH_PREPEND_ISP-1 permit 10
    match ip address prefix-list LOW_PRIOR_NET
    set as-path prepend 100

    #настройка для процесса bgp
    #для соседства с ISP-1 задаем route-map увеличивающий as-path
    #теперь route-map работает для всех входящих анонсов от ISP-1
    router bgp 200
    neighbor 192.168.11.1 route-map AS_PATH_PREPEND_ISP-1 in


###Проверка работы

    ### на маршрутизаторе Company проверяем 

    #show ip bgp, проверяем что as-path prepend сработал для 192.168.13.0 - да сработал
        Network          Next Hop            Metric LocPrf Weight Path
        r> 192.168.11.0     192.168.12.6                           0 300 100 i
        *> 192.168.12.0     0.0.0.0                  0         32768 i
        *  192.168.13.0     192.168.11.1                           0 100 100 300 i
        *>                  192.168.12.6             0             0 300 i

    #трейсим с source-addr-есом 192.168. до доступных адресов сети 192.168.13.0/24
    #идет через ISP-2 как теперь мы и хотим
        Tracing the route to 192.168.13.9
        1 192.168.12.6 20 msec 36 msec *
    #также идет через ISP-2 
        Tracing the route to 192.168.13.8
        1 192.168.12.6 28 msec 24 msec 20 msec
        2 192.168.13.8 [AS 300] 20 msec 24 msec *
