#Исходные настройки
    #EBGP настроен Company-ISP-2
    #iBGP настоен внутри Company
    #сети анонсируются согласно формулировке задания

#Решаем проблему Next-Hop
    ###Причина проблемы недоступности анонсируемых EBGP сетей
        При анонсе EBGP сетей внутри IBGP существует особенность анонса атрибута Next-Hop
        Next-Hop атрибут в анонсах не меняется относительно того какой был прислан из EBGP 
        В нашем случае адрес Next-Hop 192.168.20.3 Остается неизменным при анонсе в AS-100
    ###Пример проблемы на устройстве

    #маршруты попали в качестве анонса на внутренний маршрутизатор 
        intnet-AS-100-R#show ip bgp
        Network          Next Hop            Metric LocPrf Weight Path
        * i10.3.3.0/24      192.168.20.3             0    100      0 20 i
        * i192.168.20.0     192.168.20.3             0    100      0 20 i
    #однако в rib из bgp-table не попали, так как до Next Hop маршрута нет
        intnet-AS-100-R#show ip route bgp

    ###Решение проблемы 
        К счастью эта особенность фиксится одной командой на бордере iBGP 
        На всех маршрутизаторах объявляющих сети из EBGP для соседства с iBGP роутерами пишем Next-Hop-Self 
        В данном задании такое нужно сделать на бордере AS-100 в сторону внутреннего маршрутизатора

###проверяем работу настроек

    ###Проверяем что проблема на внутреннем роутере исчезла
    #видим что next-hop поменялся на внутреннем роутере
    #поменялся на адрес роутера с которого прилетел анонс о сетях 10.3.3.0/24 192.168.20.0/24
    intnet-AS-100-R#show ip bgp
    Network          Next Hop            Metric LocPrf Weight Path
    * i10.3.3.0/24      192.168.20.3             0    100      0 20 i
    * i192.168.20.0     192.168.20.3             0    100      0 20 i
    
    #маршрут из bgp table попал в Rib
    intnet-AS-100-R#show ip route bgp
    B    192.168.20.0/24 [200/0] via 192.168.10.2, 00:01:48
        10.0.0.0/24 is subnetted, 1 subnets
    B       10.3.3.0 [200/0] via 192.168.10.2, 00:01:48
