!
frr version 10.5
frr defaults traditional
hostname link-r
service integrated-vtysh-config
!
log syslog informational
!
##basic controlplane config
!
interface eth1
 ip address 101.0.0.10/30
 no shutdown
!

interface eth2
 ip address 102.0.0.10/30
 no shutdown
!


##BGP
router bgp 64503
 bgp router-id 2.2.2.2
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 network 103.0.0.0/22
 network 120.0.0.0/24

 neighbor 101.0.0.9 remote-as 64501
 neighbor 101.0.0.9 description bala-r

 neighbor 102.0.0.9 remote-as 64502
 neighbor 102.0.0.9 description phcert-r
!

ip route 103.0.0.0/22 Null0
ip route 120.0.0.0/24 Null0