###Исходные основные настройки маршрутизации
    #На AS-1
        #EBGP настроен между AS-1 и AS-100, AS-200, AS-300
        #Static route 200.0.0.0/24, 200.0.0.0/30, 200.0.0.4/30 настроен до 200.0.0.1
    #На AS-1000 
        #EBGP настроен с AS-100, AS-200, AS-300



###Пошаговая настройка

#AS-1 настраиваем чтобы маршрут 200.0.0.0 был менее приоритетен через AS-100, AS-200, AS-300
    #(1)делаем peer-group объединяя соседей as-100, as-200, as-300
        router bgp 1
        neighbor RESERVE_CHANNELS peer-group
    #(2)для данной peer-group создаем "as-path acl" и "route-map"
    #   таким образом route-map по acl будет делать as-path-prepend для анонсов 200.0.0.0
        ip as-path access-list 100 permit .*1000$

        route-map AS-1000-ISP-LOW-PREFER permit 10
        match as-path 100
        set as-path prepend 1 1 1
        route-map AS-1000-ISP-LOW-PREFER permit 20

    #(3)применяем route-map для входящих анонсов с соседей peer-group-ы
        router bgp 1
        neighbor RESERVE_CHANNELS route-map AS-1000-ISP-LOW-PREFER in

    #(4)делаем обновление информации маршрутов на AS-1
    #   видим что для 200.0.0.0 через as100-200-300 сделался as-path-prepend 1 1 1
        clear ip bgp * soft
        AS-1-Central#show ip bgp
        Network          Next Hop            Metric LocPrf Weight Path
        r  100.0.0.0/24     110.0.0.2                              0 300 1000 100 i
        r                   101.0.0.2                              0 200 1000 100 i
        r>                  100.0.0.2                0             0 100 i
        r  101.0.0.0/24     110.0.0.2                              0 300 1000 200 i
        r                   100.0.0.2                              0 100 1000 200 i
        r>                  101.0.0.2                0             0 200 i
        r  110.0.0.0/24     101.0.0.2                              0 200 1000 300 i
        r                   100.0.0.2                              0 100 1000 300 i
        r>                  110.0.0.2                0             0 300 i
        *  200.0.0.0        110.0.0.2                              0 1 1 1 300 1000 i
        *                   101.0.0.2                              0 1 1 1 200 1000 i
        *>                  100.0.0.2                              0 1 1 1 100 1000 i

    #(5) вывод - 200.0.0.0 гарантировано будет идти напрямую AS-1 -> AS-1000
    #    до момента пока не отвалится канал до AS-1000