###исходные данные
    #построенный ebgp с сосдеями as-64500
    #постороенная связность внутри AS-64500 на основе OSPF
    #построенный ibgp внутри AS 64500

###решение


    #делаем route-map на R4 для установки send-commuinty "no-export"
    #на приходящие анонсы о 104.0.0.0 сети от провайдера 64504
        #R4
        #создаем prefix-list селектор сети 104.0.0.0/24
        #для которой будет создан prefix-list
        ip prefix-list 10 seq 5 permit 104.0.0.0/24

        #создаем route-map устанавливающий "no-export" для анонсов с 104.0.0.0
        route-map NO_EXPORT_POL permit 10
         match ip address prefix-list 10
         set community no-export
        route-map NO_EXPORT_POL permit 20

        #назначаем route-map для соседней AS 
        #для той, которой хотим сказать не экспортировать указанный анонс
        neighbor 100.0.0.4 route-map NO_EXPORT_POL in

        #для R1,R2,R4 ibgp
        #необходимо установить отправку send-community строк между ними
        neighbor x.x.x.x send-commuinty


###Проверка решения 
    #Смотрим маршруты на провайдерах R5,R6, на отсутствие анонса 104.0.0.0/24
    #R6
    show ip bgp
    Network          Next Hop            Metric LocPrf Weight Path
    *> 100.0.0.0/23     102.0.0.2                0             0 64500 i
    *> 101.0.0.0/23     102.0.0.2                              0 64500 64501 i
    *> 102.0.0.0/23     0.0.0.0                  0         32768 
    
    #R5
    show ip bgp
    Network          Next Hop            Metric LocPrf Weight Path
    *> 100.0.0.0/23     101.0.0.2                0             0 64500 i
    *> 101.0.0.0/23     0.0.0.0                  0         32768 i
    *> 102.0.0.0/23     101.0.0.2                              0 64500 64502 i
