frr version 9.0
frr defaults traditional
hostname R2
log syslog informational

service integrated-vtysh-config


interface lo
 ip address 195.12.255.2/32

interface eth1
 ip address 10.0.20.2/30

interface eth2
 ip address 10.0.10.2/30


router bgp 100
  no bgp ebgp-requires-policy
  network 195.12.255.2/32

  neighbor 10.0.10.1 remote-as 200
  neighbor 10.0.20.1 remote-as 100
