##указано только для R1
##для R2 настройка будет зеркальной, просто смотрим на эти настройки и схему и переносим все аналогично

###проверочный ip sla до сервиса

ip sla 3
 icmp-echo 50.1.1.1 source-ip 101.0.0.2
 threshold 100
 frequency 10
ip sla schedule 3 life forever start-time now
ip sla 4
 icmp-echo 50.1.2.1 source-ip 101.0.0.2
 threshold 100
 frequency 10
ip sla schedule 4 life forever start-time now
ip sla 5
 icmp-echo 50.1.3.1 source-ip 101.0.0.2
 threshold 100
 frequency 10
ip sla schedule 5 life forever start-time now

track 3 rtr 3
delay up 10 down 15

track 4 rtr 4
delay up 10 down 15

track 5 rtr 5
delay up 10 down 15

track 6 list boolean or
object 3 not 

track 7 list boolean or
object 4 not 

track 8 list boolean or
object 5 not 



###создание условного принятия анонсов

ip access-list standard CLIENT_FILIAL_1_NETS
 permit 50.1.1.0 0.0.0.255
ip access-list standard CLIENT_FILIAL_2_NETS
 permit 50.1.2.0 0.0.0.255
ip access-list standard CLIENT_FILIAL_3_NETS
 permit 50.1.3.0 0.0.0.255
 

 
##to ISP-1
route-map INCOM-ANN-ISP-1 permit 10
  match track 3
  match ip address CLIENT_FILIAL_1_NETS
  set local-preference 200
route-map INCOM-ANN-ISP-1 permit 15

route-map INCOM-ANN-ISP-1 permit 20
  match track 4
  match ip address CLIENT_FILIAL_2_NETS
  set local-preference 200
route-map INCOM-ANN-ISP-1 permit 25

route-map INCOM-ANN-ISP-1 permit 30
  match track 5
  match ip address CLIENT_FILIAL_3_NETS
  set local-preference 200
route-map INCOM-ANN-ISP-1 permit 35


route-map INCOM-ANN-ISP-1 permit 40
  match track 6
  match ip address CLIENT_FILIAL_1_NETS
  set local-preference 100
route-map INCOM-ANN-ISP-1 permit 45

route-map INCOM-ANN-ISP-1 permit 50
  match track 7
  match ip address CLIENT_FILIAL_2_NETS
  set local-preference 100
route-map INCOM-ANN-ISP-1 permit 55

route-map INCOM-ANN-ISP-1 permit 60
  match track 8
  match ip address CLIENT_FILIAL_3_NETS
  set local-preference 100
route-map INCOM-ANN-ISP-1 permit 65






##to ISP-2
route-map INCOM-ANN-ISP-2 permit 10
  match track 3
  match ip address CLIENT_FILIAL_1_NETS
  set local-preference 100
route-map INCOM-ANN-ISP-2 permit 15

route-map INCOM-ANN-ISP-2 permit 20
  match track 4
  match ip address CLIENT_FILIAL_2_NETS
  set local-preference 100
route-map INCOM-ANN-ISP-2 permit 25

route-map INCOM-ANN-ISP-2 permit 30
  match track 5
  match ip address CLIENT_FILIAL_3_NETS
  set local-preference 100
route-map INCOM-ANN-ISP-2 permit 35


route-map INCOM-ANN-ISP-2 permit 40
  match track 6
  match ip address CLIENT_FILIAL_1_NETS
  set local-preference 200
route-map INCOM-ANN-ISP-2 permit 45

route-map INCOM-ANN-ISP-2 permit 50
  match track 7
  match ip address CLIENT_FILIAL_2_NETS
  set local-preference 200
route-map INCOM-ANN-ISP-2 permit 55

route-map INCOM-ANN-ISP-2 permit 60
  match track 8
  match ip address CLIENT_FILIAL_3_NETS
  set local-preference 200
route-map INCOM-ANN-ISP-2 permit 65


route-map INCOM-ANN-ISP-3 deny 10
 match ip address CLIENT_FILIAL_1_NETS
 match ip address CLIENT_FILIAL_2_NETS
 match ip address CLIENT_FILIAL_3_NETS
route-map INCOM-ANN-ISP-3 permit 20

route-map INCOM-ANN-IBGP permit 10
 match ip address CLIENT_FILIAL_1_NETS
 match ip address CLIENT_FILIAL_2_NETS
 match ip address CLIENT_FILIAL_3_NETS
 set local-preference 50
route-map INCOM-ANN-IBGP permit 20
