###Исходные основные настройки маршрутизации
    #На AS-1500 EBGP с AS-300
    #Внутри AS-300 настроена OSPF связность между роутерами

###Пошаговая настройка
    
    #(1) Настраиваем RouteReflector сервера

        #Router-Reflector-1 
            #создаем bgp процесс и анонсирумую в EBGP сеть
            router bgp 300
            network 100.0.0.0 mask 255.255.255.248
            #настраиваем кластер айди, чтобы при добавлении новых кластеров RR избежать петель
            bgp cluster-id 1
            #Создаем peer-group для всех RR-клинтов для простоты отправки настроек клиентам
            router bgp 300
            neighbor AS300-RR peer-group
            neighbor AS300-RR remote-as 300
            neighbor AS300-RR update-source Loopback0
            neighbor AS300-RR route-reflector-client
            neighbor AS300-RR next-hop-self
            #добавляем RR-клиента в peer-group
            #к нему автоматом создаться соседство и применятся настройки пир-группы
            neighbor 10.0.10.10 peer-group AS300-RR

        #Router-Reflector-2 
            #аналогичные настройки как и для RR-1