

               net 103.0.0.0/22
               net 120.0.0.0/24
                      |
   |---------------cloud-r-------------------------|
   |                                               |
bala-r------------------------------------------ phcert-r   
   |                                               |
   |-[nat-outside]fa0/0-link-r-fa0/1[nat-outisde]--|
                         |
                     [nat-inside]
                     [ip nat inside source route-map BALAGAN interface Fa0/0 overload]
                     [ip nat inside source route-map PH_CERT interface Fa0/1 overload]
                         |
                         |
                    net 10.0.1.0/24
                    net 10.0.2.0/24       


INFO:

on link-r
    - default gw is bala-r
    - nat local-nets to both ISP
    - default gw is balagan-r

on cloud-r
    - routes added via bgp from ISP bala and phcerts

on bala-r and phcert-r 
    - routes added via bgp from ISP-s and cloud-r



TASK:
    (1)for link-r make SLA which 
      - checks reacheability of 103.0.0.10/103.0.0.20 from bala-r
    (2)for link-r make PBR which
      - links to created SLA
      - make default ISP as bala-r 
        - if 103.0.0.x not reacheable through bala-r make traffic go through phcert-r

РЕШЕНИЕ:

ip route 0.0.0.0 0.0.0.0 101.0.0.1

#связка sla которые необходимы для 
#подтверждения необходимости переключения на 2-ой запасной канал

#проверка НЕ работоспособности основного канала

#проверка sla icmp-echo до сервиса в облаке
ip sla 1
 icmp-echo 103.0.0.10 source-interface FastEthernet0/1
 threshold 500
 frequency 10
ip sla schedule 1 life forever start-time now

#проверка sla icmp-echo до линковой сети phcert
#не стал делать, так как в задании не требуется


#трек 1 отслеживатель состояния основного канала и
#трек 2 инвертирующий значение трека 1
track 1 rtr 1
 delay down 25 up 10

track 2 list boolean or
 object 1 not

#acl селектор адресов к которых применяется политика
ip access-list extended LAN_POLICY
 permit ip 10.0.1.0 0.0.0.255 any 
 permit ip 10.0.1.0 0.0.0.255 any


##эти селекторы ненужны, так как не отбрасываем какой-либо трафик по заданию если он не из 10.0.х.х
#acl селектор адресов которые при необходимости маршрутизировать по rib
#остальные пакеты будут отбрасываться 
#ip access-list extended DROP_Traffic_selector
# deny   ip 10.0.1.0 0.0.0.255 any
# deny   ip 10.0.2.0 0.0.0.255 any
# deny   ip 101.0.0.1 0.0.0.0 any 
# deny   ip 102.0.0.1 0.0.0.0 any 
# permit ip any any


#если track 2 false - работает rib default gw - 0.0.0.0 via 101.0.0.1
#если track 2 true - работает полиси-роут next-hop - 0.0.0.0 via 102.0.0.1
#проверка жив ли запасной канал не делается, переключаем с доверием что второй канал жив
route-map Switch-to-Reserv-PhCert permit 10
 match ip address LAN_POLICY
 set ip next-hop verify-availability 102.0.0.1 10 track 2

##этот полиси роут ненужен, так как в задании не указано дропать трафик
#route-map Switch-to-Reserv-PhCert permit 30
# match ip address DROP_Traffic_selector
# set interface Null0