!
frr version 10.5
frr defaults traditional
hostname link-r
service integrated-vtysh-config
!

interface lo
 ip address 100.0.0.254/32
 no shutdown
!

interface eth1
 description bala-r
 ip address 101.0.0.2/30
 no shutdown
!

interface eth2
 description phcert-r
 ip address 102.0.0.2/30
 no shutdown
!

ip route 100.0.0.0/24 Null0

router bgp 64500
 no bgp ebgp-requires-policy

 network 100.0.0.0/24

 neighbor 101.0.0.1 remote-as 64501
 neighbor 102.0.0.1 remote-as 54502
!