
ЗАДАНИЕ

Необходимо реализовать
    - настроить IBGP внутри автономной системы 64500, то есть это подразумевает
        - настройка EBGP на бордер маршрутизаторах R1,R2,R7 и получение маршрутов от пограничных маршрутизаторов
        - далее через IBGP распространение полученных маршрутов среди R1,R2,R4,R5

Нулевым пунктом - опрделим сети каждой из AS на схеме 
    R1,R2,R3,R4 - as 64500    announce-net:100.0.0.0/23
    R5          - as 64501    announce-net:101.0.0.0/23
    R6          - as 64502    announce-net:102.0.0.0/21
    R8          - as 64503    announce-net:103.0.0.0/22
    R7          - as 64504    announce-net:104.0.0.0/24

Первым пунктом - необходимо реализовать EBGP на пограничных маршрутизаторах AS-64500
    - R1(64500) соседство с R5(64501)
    - R2(64500) соседство с R6(64502)
    - R4(64500) соседство с R7(64504)
    После этого R1,R2,R4 будут знать маршруты от своих провайдеров



Вторым пунктом - необходимо реализовать IBGP внутри R1,R2,R3,R4, то есть 
    - выделить внутреннюю сеть 10.0.0.0/8 для внутренних подсетей IBGP R1,R2,R3,R4
    - выделить сеть для loopback интерфейсов R1,R2,R3,R4
    - сделать связность R1,R2,R3,R4 по IGP протколу для возможности построения IBGP
    - построить соседство IBGP R1,R2,R3,R4 каждого с каждым 
    - распротранить по этим соседствам маршруты полученные от провайдеров по EBGP


Третьим пунктом - проверка конфигурации
    - проверить что внутренняя AS-64500 выполняет транзит трафика провайдеров R5,R6,R7,R8
        - т.е. проверить  свяность R7----as64500-----(R5,R6,R8) и в обратную сторону


                        (64503)
                         --R8--
                --------|     |---------
                |                      |
            101.0.0.8/30            102.0.0.8/30    
                |                      |
         (64501)R5-----101.0.0.4/30----R6(64502)
                |                      |
            101.0.0.0/30           102.0.0.0/30
                |                      |
                |                      |
                |                      |
         (64500)R1-----10.0.12.0/24----R2(64500)  
                |                      |
            10.0.14.0/24           10.0.23.0/24
                |                      |
         (64500)R4-----10.0.34.0/24----R5(64500)
                |
                |
                |
           100.0.0.4/30
                | 
                R7(64504)


