!
frr version 10.5
frr defaults traditional
hostname link-r
service integrated-vtysh-config
!
log syslog informational
!

##basic controlplane confi
interface eth1
 ip address 101.0.0.2/30
 no shutdown
!

interface eth2
 ip address 102.0.0.2/30
 no shutdown
!

###routing
#default gw via bala
ip route 0.0.0.0/0 101.0.0.1


##BGP
