


###advertise-map ... exist-map ... не выполняет фильтрацию

    #(1) если вы пропишете в advertise-map следующий route-map
    #    то deny не сработает как запрет 
    #    advertise-map работает исключительно чтобы указать какие сети будут анонсится
    #    в случае срабатывания условия exist-map
        route-map ABC deny 10
            match ip address...
        route-map ABC permit 20
            match ip address...
        
        neighbor ISP-1 advertise-map ABC exist-map EXIST-MAP

    #(2) для того чтобы задать фильтрацию необходимо использовать 
    #    стандартный механизм фильтрации -- neighbor ISP-1 route-map FILTER out

        route-map FILTER deny 10
            match ip address...
        route-map FILTER permit 20
            match ip address...

        neighbor ISP-1 route-map FILTER out

    #(3) по итогу задаем 
    #    условный анонс через "advertise-map ... exist-map ..."
    #    и фильтрацию через " route-map ... out" 

        neighbor ISP-1 advertise-map ABC exist-map EXIST-MAP
        neighbor ISP-1 route-map FILTER out
