
###исходные данные
    #построенный ebgp с сосдеями из AS-64500
    #постороенная связность внутри AS-64500
    #построенный ibgp внутри AS 500

###решение

###R1

    ###Создаем IP SLA для отслеживания доступности 103... сервиса###
    
    #анонс о сервисе 103... уже должен был прийти от ISP-1
    #будем отслеживать доступность его через основого провайдера ISP-1
        ip sla 1
        icmp-echo 103.0.0.1 source-ip 101.0.0.2
        threshold 100
        frequency 10
        ip sla schedule 1 life forever start-time now

        #крепим трек к sla, чтобы отслеживать этот самый sla
        track 1 rtr 1
        delay up 10 down 15

    ###Создаем маршрут болванчик, для сигнала up/down ip SLA###
    
        #делаем условный статик роут, который будет или не будет в rib в зависимости от up/down IPS SLA
        #на проверке наличия/отстуствия этого маршрута будем определять через кого анонсить 150...

        ip route 172.255.255.255 255.255.255.255 Null track 1


    ###Создаем 2 route-map для условных анонсов

        #Первый Route-map
        #Route-map проверящий наличие условного route-а
        #он будет условием анонсить или не анонсить 150...
        access-list 20 permit 172.255.255.254
        
        route-map EXIST-MAP permit 10
            match ip address 20

        #Второй Route-map
        #Этот Route-map просто определяет что 150... будет условно анонситься
        #Все остальные анонсы не попавшие под этот route-map будут анонситься обычно
        access-list 10 permit 150.0.0.0 0.0.0.3
        
        #в сторону ISP-1
        route-map ADVER-POL-ISP-1 permit 10
        match ip address 10

        #в сторону ISP-2
        route-map ADVER-POL-ISP-2 permit 10
        match ip address 10


    ###Для соседства с ISP-1 и ISP-2 задаем условный анонс

    #с помощью спец. ключевого слова exist-map non-exist-map можно задать условные анонсы
    #  exist-map смотрит в route-map который мы указалиэ
    #  он ищет в bgp table маршрут который указан в route-map 
    #  в случае exist-map если в bgp table есть маршрут, то анонс отправляется

    #в сторону ISP-1- если dummy-route существует, то анонсим 150.. в ISP-1
    neighbor 101.0.0.5 advertise-map ADVER-POL-ISP-1 exist-map EXIST-MAP

    #в сторону ISP-2- если dummy-route НЕ существует, то анонсим 150.. в ISP-2
    neighbor 105.0.0.5 advertise-map ADVER-POL-ISP-2 non-exist-map EXIST-MAP


    ###Зеркально делаем на R2

    ###Проверяем
        #НА ISP-1 bgp table имеет анонсы 150...
        #НА ISP-2 bgp table не имеет анонсы 150...
        #при выключении сервиса 103.. в сторону ISP-1, падает IP SLA, анонсы появляются на ISP-2

    

    ###Дополнительно 

        #Запрещаем анонсы 172... dummy роутов любым соседям
            #конфига нет, добавил в исходную конфигурацию в сосденей паке