frr version 10.3.1
frr defaults traditional
hostname debian
log syslog informational
no ip forwarding
no ipv6 forwarding
service integrated-vtysh-config
!
router bgp 3
 no bgp ebgp-requires-policy
 neighbor 192.168.20.10 remote-as 100
 neighbor 192.168.30.10 remote-as 200
exit
!
