


     |----r2----|
     |          |
r1---          r4-----r5
     |          |
     |----r3----|


INFO:

on r1 
    - default gw is r2
    - traffic to r5 comes as follows: r1-r2-r4-r5

on r4 
    - default gw is r2

on r5
    - default gw is r4
    - traffic to r1 comes as follows: r5-r4-r2-r1


TASK:
    make traffic going from r5 to r1 go through r3
    you allow to do config on r4 router


ADDITION:
    #отличие next-hop  и default next-hop
    
    #применит policy - next-hop 192.168.3.3 не смотря в rib
      route-map BACK-to-200.1
      match ip address 100 
      set ip next-hop 192.168.3.3 
    
    #сначала произойдет просмотр rib на наличие точного(/32) маршрута 192.168.3.3    
    #если такого нет применит policy - next-hop 192.168.3.3
      route-map BACK-to-200.1
      match ip address 100 
      set ip default next-hop 192.168.3.3 