


        ann.net:180.0.0.0/24
              |
   |------R5(AS-400)------|
   |                      |
10.0.10.8/30           10.0.10.12/30
   |                      |
R3(AS-300)              R4(AS-200)
ann.net:200.0.0./24     ann.net:100.0.0.0/24
   |                      |
   |                      |
 10.0.10.4/30            10.0.10.0/30
   |                      |
   |                      |
  R1(AS-100)------------R2(AS-100)
                |
      ann.net:195.12.0.0/16
    
    
         



INFO:

На R3 для сети 195.12.0.0/16 существует два пути через R5 и R1:
>show ip bgp table
>195.12.0.0/16  via 10.0.10.6
*>              via 10.0.10.9

А на R4 до сети 195.12.0.0/16 всего один путь
На R3 для сети 195.12.0.0/16 существует два пути через R5 и R1:
>show ip bgp table
>195.12.0.0/16  via 10.10.10.2


TASK:


    Объясните причину количества маршрутов до 195.16.0.0/16 на R3 и R4 
    описанного в INFO.
    Почему на одном есть запАсный маршрут, а на другом всего один

    Для решение удобно воспользовться bgp-dashobard доступный по
    <адрес-mgmt-сети-контейнера>:8088. Для этого поднимите containerlab
    лабу во вложении и зайдите в веб интерфейс дашборда, лаба уже настроена.


КОНФИГ РЕШЕНИЯ:
Пояснение: Задача не требует конфигурации, необходимо ответить на вопрос


R5 получает два маршрута в сеть 195.12/16: один через R3, другой через R4.
Они равнозначны, но R5 должен выбрать только один из них. Делается это на основе IP-адреса, который меньше у R4.
Соответственно R5 анонсирует своим соседям только один маршрут через R4 до данной сети. R4 его не получает, разумеется, а вот R3 он этот маршрут изучит.

В итоге R3 получит два анонса об этой сети, а R4 только один.


Убедимся на практике

#R5 имеет 2 маршрута до 192.12, где 10.0.10.10 предпочтительнее
# так как 10.0.10.10 < 10.0.10.14

r5# show ip bgp

Origin codes:  i - IGP, e - EGP, ? - incomplete
RPKI validation codes: V valid, I invalid, N Not found

     Network          Next Hop            Metric LocPrf Weight Path
 *>  100.0.0.0/24     10.0.10.14               0             0 200 i
 *>  180.0.0.0/24     0.0.0.0                  0         32768 i
 *>  195.12.255.1/32  10.0.10.10                             0 300 100 i
 *                    10.0.10.14                             0 200 100 i
 *>  195.12.255.2/32  10.0.10.10                             0 300 100 i
 *                    10.0.10.14                             0 200 100 i
 *>  200.0.0.0/24     10.0.10.10               0             0 300 i
 *                    10.0.10.14                             0 200 100 300 i

#r4 получил анонс который пришел ему от R5 и от R2

r4# show ip bgp

     Network          Next Hop            Metric LocPrf Weight Path
 *>  100.0.0.0/24     0.0.0.0                  0         32768 i
 *>  180.0.0.0/24     10.0.10.13               0             0 400 i
 *>  195.12.255.1/32  10.0.10.2                              0 100 i
 *                    10.0.10.13                             0 400 300 100 i
 *>  195.12.255.2/32  10.0.10.2                0             0 100 i
 *                    10.0.10.13                             0 400 300 100 i
 *>  200.0.0.0/24     10.0.10.2                              0 100 300 i
 *                    10.0.10.13                             0 400 300 i

#r3 получил только анонс от R1, а от R5 не получил
#так как R5 маршрут до сети 195.12 выбрал через R3 

r3# show ip bgp

     Network          Next Hop            Metric LocPrf Weight Path
 *>  100.0.0.0/24     10.0.10.9                              0 400 200 i
 *                    10.0.10.6                              0 100 200 i
 *>  180.0.0.0/24     10.0.10.9                0             0 400 i
 *>  195.12.255.1/32  10.0.10.6                0             0 100 i
 *>  195.12.255.2/32  10.0.10.6                              0 100 i
 *>  200.0.0.0/24     0.0.0.0                  0         32768 i