frr version 9.0
frr defaults traditional
hostname R3
log syslog informational

service integrated-vtysh-config


interface lo
 ip address 200.0.0.1/32

interface eth1
 ip address 10.0.10.5/30

interface eth2
 ip address 10.0.10.10/30


router bgp 300

  no bgp ebgp-requires-policy
  network 200.0.0.0/24

  neighbor 10.0.10.6 remote-as 100
  neighbor 10.0.10.9 remote-as 400

ip route 200.0.0.0/24 Null0