
!
hostname Router
!
boot-start-marker
boot-end-marker
!
!
no aaa new-model
memory-size iomem 5
ip cef
!
!
!
!
!
multilink bundle-name authenticated
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
archive
 log config
  hidekeys
!
!
!
!
!
!
!
!
interface Loopback0
 ip address 180.0.0.1 255.255.255.255
!
interface FastEthernet0/0
 ip address 10.0.10.9 255.255.255.252
 duplex auto
 speed auto
!
interface FastEthernet0/1
 ip address 10.0.10.13 255.255.255.252
 duplex auto
 speed auto
!
router bgp 400
 no synchronization
 bgp log-neighbor-changes
 network 180.0.0.0 mask 255.255.255.0
 neighbor 10.0.10.10 remote-as 300
 neighbor 10.0.10.14 remote-as 200
 no auto-summary
!
ip forward-protocol nd
ip route 180.0.0.0 255.255.255.0 Null0
!
!
ip http server
no ip http secure-server
!
!
!
!
!
!
!
control-plane
!
!
!
!
!
!
!
!
!
!
line con 0
line aux 0
line vty 0 4
 login
!
!
end
