Current configuration : 1642 bytes
!
version 12.4
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
!
hostname Router
!
boot-start-marker
boot-end-marker
!
!
no aaa new-model
memory-size iomem 5
ip cef
!
!
!
!
!
multilink bundle-name authenticated
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
archive
 log config
  hidekeys
!
!
!
vlan internal allocation policy ascending
!
!
!
!
!
interface Loopback0
 ip address 102.0.0.254 255.255.255.255
!
interface FastEthernet0/0
 ip address 102.0.0.1 255.255.255.252
 speed 100
 full-duplex
!
interface FastEthernet0/1
 ip address 102.0.0.9 255.255.255.252
 speed 100
 full-duplex
!
interface FastEthernet1/0
 no switchport
 ip address 101.0.0.6 255.255.255.252
 duplex full
 speed 100
!
interface FastEthernet1/1
!
interface FastEthernet1/2
!
interface FastEthernet1/3
!
interface FastEthernet1/4
!
interface FastEthernet1/5
!
interface FastEthernet1/6
!
interface FastEthernet1/7
!
interface FastEthernet1/8
!
interface FastEthernet1/9
!
interface FastEthernet1/10
!
interface FastEthernet1/11
!
interface FastEthernet1/12
!
interface FastEthernet1/13
!
interface FastEthernet1/14
!
interface FastEthernet1/15
!
interface Vlan1
 no ip address
!
router bgp 54502
 no synchronization
 bgp log-neighbor-changes
 network 102.0.0.0 mask 255.255.255.0
 neighbor 101.0.0.5 remote-as 64501
 neighbor 102.0.0.2 remote-as 64500
 neighbor 102.0.0.10 remote-as 64503
 no auto-summary
!
ip forward-protocol nd
ip route 102.0.0.0 255.255.255.0 Null0
!
!
ip http server
no ip http secure-server
!
!
!
!
!
!
!
control-plane
!
!
!
!
!
!
!
!
!
!
line con 0
line aux 0
line vty 0 4
 login
!
!
end
